name: simi
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  file_picker: ^6.1.1
  image_picker: ^1.0.0
  http: ^1.1.0
  shared_preferences: ^2.2.0
  google_sign_in: ^6.1.5
  flutter_web_auth: ^0.4.0
  url_launcher: ^6.1.10
  lottie: ^2.7.0
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  flutter_image_compress: ^2.1.0
  path_provider: ^2.1.2
  carousel_slider: ^4.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1



flutter:
  uses-material-design: true

  assets:
    - assets/payment.png
    - assets/google.png
    - assets/pasar.jpeg
    - assets/dibakar.png
    - assets/fotodashboard.png
    - assets/fotodashboard2.png
    - assets/jalaniSumpah.jpeg
    - assets/mandiri.png
    - assets/bri.png
    - assets/bni.png
    - assets/logoKonfirm.png
    - assets/lottie/success.json
    - assets/logoSimi.png
    - assets/lottie/walking.json
    - assets/lottie/payment.json
    - assets/lottie/transaction.json
    - assets/lottie/forgot_password.json
    - assets/lottie/data.json
    - assets/lottie/classtidakbisadiakses.json
    - assets/lottie/nodata.json
    - assets/lottie/batalkelas.json
    - assets/lottie/nilai.json

flutter_icons:
  android: true
  ios: false
  image_path: "assets/logoSimi.png"
